### ISSUE TITLE
Add failure strategy

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#1]
Add configuration options for failure handling (the Docker container stops running). Possible handling:
- Restart the container endlessly
- Restart the contaienr X times and then shut down
- Shutdown immidiatly

Currently, if a Docker image breaks, the server just keeps running without application.

**Comment by bobbruno** [comment]
We should support onetime tasks (like jobs running once per week) and the instance should therefore shutdown for such cases after the Docker process exited.

**Comment by tuxlife** [comment]
+1

**Comment by Raffo** [comment]
The current recommended approach is: expose an endpoint from the application and monitor it (with ZMON for example).
