### ISSUE TITLE
rkhunter

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#10]
during build, index filesystem, during runtime check filesystem

**Comment by hjacobs** [comment]
This should be optimized:

Running rkhunter during boot takes about one minute,
that's far too slow! we should run it only in the background

**Comment by apfeiffer85** [comment]
yes your right, i will cancel the initial check on boot time and will configure a cron for the check.

**Comment by apfeiffer85** [comment]
rkhunter is now integrated but we have a follow-up issue: #87
