### ISSUE TITLE
variable file size or rotation rate for /var/log/application.log

### ISSUE THREAD

**Issue by chutium** [zalando-stups/taupage#107]
Since all the content of /var/log/application.log are sent to scalyr or logentries, we want to limit the size of those logs on local disk of deployed EC2 instance, or decrease the rotation rate.

It would be better if those can be done as Taupage settings in YAML file.

**Comment by apfeiffer85** [comment]
we could also rotate the application.log daily instead of weekly. And if this is not enough we could create a option in the yaml file where you can set the "file size limit" to rotate the file.

**Comment by chutium** [comment]
I would like to use this limit as an option, maybe there are some appliances that the owner do not want to send the logs out, and just keep it on disk, then daily rotation is maybe too short.

**Comment by marek-obuchowicz** [comment]
File size limit and/or change logrotate period would be very helpful. This issue can become very critical, as application.log fills for us the diskspace after 30 hours and we can't control anything that's not in docker container. Note that when disk is full, we can't ssh to machine (granting-service fails).

Note, you should notify scalyr-agent after rotating files.

**Comment by marek-obuchowicz** [comment]
Is there any update for that? The rotation based on size would be very helpful for us. One of our apps got crazy, effectively generated gigs of logs and this made instance unavailable (couldn't login via piu because granting-service did not create account for login)
