### ISSUE TITLE
Send RAM/Memory/Diskspace Usage to Cloudwatch

### ISSUE THREAD

**Issue by drummerwolli** [zalando-stups/taupage#108]
Cloudwatch is not monitoring by default the Memory Usage. Since this is a strongly needed metric, we could implement this in taupage directly to send this to cloudwatch all the time. An example script could look like this: 

http://arr.gr/blog/2013/08/monitoring-ec2-instance-memory-usage-with-cloudwatch/
(i tried his script, it is not working for me because of a failing boto call, maybe it would be also better to use boto3 nowadays for this)

also taupage would need to create a role which allows it to send metrics to cloudwatch.

What do you think?

**Comment by drummerwolli** [comment]
also disk space of the root volume could be included that way.

**Comment by Jan-M** [comment]
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/mon-scripts-perl.html

probably this is a better starting point to use, as they come from Amazon and provide this.

But there are some experiments in using the prometheus "agent", I will ask around.

**Comment by chutium** [comment]
just find this script from AWS, which we can deploy into taupage image:
http://aws.amazon.com/code/8720044071969977 to enable some "CloudWatch Custom Metrics"

no idea why cloudwatch do not collect these informations by default

**Comment by femueller** [comment]
Looks good, I think we can integrate them very soon
