### ISSUE TITLE
Mount /var/log into the docker container  

### ISSUE THREAD

**Issue by apfeiffer85** [zalando-stups/taupage#110]
make this configurable: 
https://github.com/zalando-stups/taupage/blob/master/runtime/opt/taupage/runtime/Docker.py#L109

Could be a option in the taupage.yaml

**Comment by hjacobs** [comment]
Yes, please make this configurable --- always mounting /var/log may break Docker images relying on internal /var/log folder (e.g. the "Odd Bastion host" image)
