### ISSUE TITLE
Only run awslogs-nanny.sh when needed

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#114]
There are frequent syslog messages about awslogs-nanny.sh even if no Cloud Watch logs are used --- awslogs-nanny.sh should run via CRON if Cloud Watch logs are enabled:

    CRON[1681]: (root) CMD (/var/awslogs/bin/awslogs-nanny.sh > /dev/null 2>&1)

**Comment by femueller** [comment]
This was fixed by #115
