### ISSUE TITLE
Use Token Service only as fallback for non-confidental OAuth clients (client_id = null)

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#116]
To avoid one more layer of potential problems (e.g. rate limits) we should circumvent the Token Service in the default case and use the OAuth 2 provider endpoint directly.

Changes are needed in the "get_token" method.

**Comment by hjacobs** [comment]
We can use the existing "tokens" library for this: https://github.com/zalando-stups/python-tokens

**Comment by prayerslayer** [comment]
Fixed with #117
