### ISSUE TITLE
Add logrotate for application.log

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando-stups/taupage#128]
As application log grows (during normal operation - we're using java app which is pretty verbose), it eventually fills up all available diskspace. This logfile should be rotated. Please note that scalyr must know that file has been rotated, otherwise it stops forwarding logs.

Please mark it as high priority. It caused some of our instances to get isolated - when disk is full, the "granting" service fails and it's impossible to login to free up some diskspace.

**Comment by apfeiffer85** [comment]
i guess this ticket is related to #107 

currently we rotate the application.log weekly if this is bot enough you can configure it if #107 is completed.

**Comment by marek-obuchowicz** [comment]
It's effectively duplicate to #107
