### ISSUE TITLE
CloudWatch: monitor other disk partitions

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando-stups/taupage#135]
Please add the CloudWatch metrics about the disk usage also for EBS mountpoints listed in taupage user-data, if they are provided

**Comment by femueller** [comment]
As a note for this feature: We could basically add a wrapper on top of the provided cloudwatch metrics script, which parses all partitions and adds them automatically to the cronjob.

It could be like this:

    for i in `df -h | grep ^/dev | awk  '{print $6}'`; do echo $i; done

and add it to:

    /etc/cron.d/mon-put-instance-data-cloudwatch (--diskpath=$i)

**Comment by femueller** [comment]
This would be my proposal for "fixing" this issue. As there will be soon a proper release by AWS, which covers this topic I am not really sure if we should integrate this.

**Comment by femueller** [comment]
@marek-obuchowicz What's your opinion about this feature? Do you need this for now? Otherwise I would wait for AWS to integrate it.

**Comment by femueller** [comment]
I'll close this, since nothing has happened here and we're expecting to get this fixed by AWS in the close future.
