### ISSUE TITLE
Taupage AMI cron time

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/taupage#138]
Because all server use the same AMI, all cron jobs are executed in the same minutes.

```
# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
 
```
Can we change it, to a random time? Would be better to avoid that a whole stack execute the job on the same time.

**Comment by femueller** [comment]
This would add more complexity right now than we could clearly maintain. I will close this for now, because if jobs were run, they should only be executed inside the Docker container.
