### ISSUE TITLE
Reserve disk space to always enable ssh

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/taupage#139]
In order to always have the chance to debug our application,
reserve disk space to always enable ssh.

Idea: key and passwd on ramfs??

**Comment by drummerwolli** [comment]
+1 for the issue, no idea though

**Comment by mrandi** [comment]
I would maybe opt for tmpfs, we are than sure that we will not let the system hangs if we are write more than defined.

```$ mkdir -p /mnt/tmp```
```$ mount -t tmpfs -o size=20m tmpfs /mnt/tmp```

**Comment by marek-obuchowicz** [comment]
+1 for this issue

**Comment by apfeiffer85** [comment]
I guess this issue was solved by the PR #150
