### ISSUE TITLE
Docker container does not always start up on boot 

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#14]
Check and fix: Docker container does not always start up on boot (devicemapper errors), but works on second try

**Comment by femueller** [comment]
This has been fixed in https://github.com/zalando-stups/taupage/commit/6ac52c5b917434ca6a573b02b1f224fa7b5c97af.
As a workaround we've been triggering a restart of the Container for a maximum of three tries, since this seems to be a Docker bug.
