### ISSUE TITLE
Hourly default application log rotation

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/taupage#141]
Would be easier to default rotate the application logs also hourly.
Right now is not possible to reduce from day to hour via config.

https://github.com/zalando-stups/taupage/blob/87e671c466ad1109215d811733f4be8b151d9e17/runtime/opt/taupage/init.d/86-adjust-application-logrotate#L18

**Comment by apfeiffer85** [comment]
Now it is possible to also set hourly logrotate.
