### ISSUE TITLE
Add more Logs for send out to log-providers

### ISSUE THREAD

**Issue by drummerwolli** [zalando-stups/taupage#143]
It would be nice to configure in the Taupage Config Yaml additional Logs in the Docker container, which will be send out seperately to the log providers. Adding other logs with "tail -f" puts them all without overview in one log, which makes it cumbersome to distinguish them (think 10 diferent logs of several applications).

first idea: mount from taupage the location of the log in the docker and tell the log-agent to send those, too.

**Comment by hjacobs** [comment]
I'm personally not a fan of adding this feature to Taupage. One application (Docker image) should usually run only one process and just print to STDOUT. Line prefixes could provide some means of splitting logs.

**Comment by drummerwolli** [comment]
for leightweight applications and rest services, this might apply and i would agree for those. but more heavyweight software might work differently; additionally you as a deployer may have not coded the application (e.g. other OS software, or even proprietary stuff) and you can't adjust the output, etc. E.g. kafka or zookeeper/exhibitor already write 3-4 different logs, sometimes depending on the role the broker/node is taking over. i think databases would also fit in this category ...

this is not a high prio feature request, though. and i personally would like to keep things as simple as possible. but i think having a decent, cleaned up overview about complex systems is more what we aim here for and should be favoured.

**Comment by marek-obuchowicz** [comment]
Lounge team was also considering it, as Elasticsearch logging uses several different files. We're also using JVM GC logging, which, if logged to external file, could be easily tagged/filtered in Scalyr. At the moment it comes out to stdlog and the SLF4j parser in Scalyr fails to correctly handle GC messages (we can't alter logformat of those)

**Comment by Raffo** [comment]
We currently support AppDynamics and it's possible to customize this via: https://github.com/zalando-stups/taupage/blob/ba18617ae8f9a01032d92acaf615f4a39d7f9077/runtime/opt/taupage/runtime/Docker.py#L160-L163
