### ISSUE TITLE
remove/rotate pushed gzip audit logs

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/taupage#147]
Would be nice to rotate or remove gzip audit logs after pushed it.
https://github.com/zalando-stups/taupage/blob/master/runtime/opt/taupage/bin/push-audit-logs.py#L38

**Comment by apfeiffer85** [comment]
Is it ok to directly remove the file if the push works well ? 
I guess this is the simplest solution. ;-)

**Comment by mrandi** [comment]
I think it would be also fine!
@hjacobs what do you think??

**Comment by bocytko** [comment]
@mrandi any progress on the issue?

**Comment by hjacobs** [comment]
Actually the current settings look OK for me:

```
$ cat ./runtime/etc/logrotate.d/auditlog 
su root syslog

/var/log/audit.log
{
        rotate 48
        hourly
        missingok
        notifempty
        compress
        sharedscripts
        postrotate
                reload rsyslog >/dev/null 2>&1 || true
        endscript
}
```

=> Rotated hourly and keep 48 files (two days).

**Comment by hjacobs** [comment]
@bocytko can you tell us where you see audit logs exploding?

They are only kept for two days and GZIPed (see above) ..

**Comment by bocytko** [comment]
It's not about exploding. They're gzipped and never removed, so they're theoretically a threat to disk consumption:

```
$ ls -l /var/log/audit.log.1* | wc -l
1276
```

**Comment by apfeiffer85** [comment]
Just to clarify, it is not the normal /var/log/audit.log and the lorotate for that. it is the "pushed" audit.log logfile. e.g audit.log.1.gz-pushed-2016-01-**** 

I will delete the file after it was pushed.
