### ISSUE TITLE
Set TCP timeouts explicitly

### ISSUE THREAD

**Issue by bocytko** [zalando-stups/taupage#153]
The TCP timeout is set to the default: 2h.

```
$ cat /proc/sys/net/ipv4/tcp_keepalive_time 
7200
```

A value in the range of minutes (for example: 1 minute) is desired.

**Comment by szuecs** [comment]
I would suggest something like we had on our databases, before.

if 3 keepalives are not send connection is considered dead:

    net.ipv4.tcp_keepalive_probes = 3

keepalive interval in seconds (both should be set!)

    net.ipv4.tcp_keepalive_time = 60
    net.ipv4.tcp_keepalive_intvl = 90

http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html

**Comment by hjacobs** [comment]
Sounds like a good suggestion, I think we would  need to discuss the actual parameter values (I know too less about this topic to have an opinion).

Maybe the system and database experts can jump in here?

**Comment by szuecs** [comment]
When do we get progress on this issue?

**Comment by hjacobs** [comment]
@tuxlife @apfeiffer85 @femueller any comments/suggestions on this issue?

**Comment by femueller** [comment]
Definitely makes sense to me. I think we can implement this soon.
