### ISSUE TITLE
Consider to pass AWS userdata to Dockercontainer as environment variables

### ISSUE THREAD

**Issue by femueller** [zalando-stups/taupage#156]
Consider to pass AWS userdata variables and values like [availablity zone](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html) to the Docker container as environment variables.

**Comment by hjacobs** [comment]
We should discuss this! I believe this might be a endless story: everybody might some day require one specific value from AWS's metadata service, so how do we distinguish between stuff we inject as environment variables and stuff we don't? We certainly cannot push all data as environment variables.

**Comment by hjacobs** [comment]
IIRC now we only inject APPLICATION_ID and CREDENTIALS_DIR and these are AWS-independent.

**Comment by femueller** [comment]
I agree too and as we have discussed, I will close this issue.
The metadata service is available and can be queried if it's required.

**Comment by hjacobs** [comment]
:+1:
