### ISSUE TITLE
create common audit infrastructure

### ISSUE THREAD

**Issue by vetinari** [zalando-stups/taupage#170]
Currently every team has to create their own way of saving audit log messages from within the container to some "safe storage". This should be built in the taupage image. One way could be to mount  a directory from the host with a socket where the app in the docker container can write to. The messages are read by some script in the host into e.g. /var/log/application-audit.log and the script which sends the /var/log/audit.log content also copies these messages to a central place.

**Comment by hjacobs** [comment]
I'm against integrating that feature into Taupage, Taupage also has enough features --- application specific auditing logs should be handled by the application. Some applications e.g. have databases where audit logs can be stored...
