### ISSUE TITLE
Set sane defaults for rotating of logfiles

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando-stups/taupage#172]
in commit ce88fc75aa9d8755e9c4a1fa17b25dade5d8a398 the possibility to rotate on size was introduced.

However, the default is still that it only rotates on time. As the space for Taupage is limited, it might be best to limit the size of any single log to a decent amount.

With a rotate of 4, diskspace for Taupage being limited to a few GB, I would propose to change the
default from none to

    size 256M

**Comment by femueller** [comment]
I'll close it, since the PR has been merged.
