### ISSUE TITLE
Ability to specify parameters (overcommit, shmmax)

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando-stups/taupage#175]
The trigger for this issue is a spilo issue: https://github.com/zalando/spilo/issues/42

We would like to be able to configure some parameters for applications running on top of Taupage.
If we can specify it in some way in Docker it would be great, however I'm not sure that's possible.

The following parameters are normally tuned:
- `kernel.shmall`: physical_pages / 2
- `kernel.shmmax`: physical_pages \* pagesize / 2
- `vm.dirty_background_ratio`: 1
- `vm.dirty_ratio`: 2
- `vm.overcommit_memory`: 0
- `vm.swappiness`: 0

**Comment by feikesteenbergen** [comment]
Could you provide some feedback on this issue? Do you want to implement this? We really need this.

**Comment by hjacobs** [comment]
:+1: for the tuning, not sure how to implement it (configuration should be via Taupage properties)
