### ISSUE TITLE
Set TOKENINFO_URL environment variable for "Plan B"

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#177]
We will need to set the OAuth2 Token Info URL in Taupage to transparently switch to our local "planb-agent" sidecar.

**Comment by hjacobs** [comment]
TODO: we should allow overwriting the environment variable

**Comment by lukasniemeier-zalando** [comment]
:+1: on if the variable is set in the user data definition Taupage should not overwrite it (applies to any variable) - might confuse the user (or even break stuff in case the variables are used in a non-standard-way).

**Comment by hjacobs** [comment]
Should be fixed in https://github.com/zalando-stups/taupage/commit/fe2d3a1bf90e023db1ff150d522810b60c87a4bb
