### ISSUE TITLE
Please add an option to enable terminal in the yaml

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/taupage#178]
There should be a possibility to run the container as if it was started with `-t` option.
Currently, for example, when I do

```
$ docker exec -it taupageapp bash
```

and then try using `less`, it complains:

```
WARNING: terminal is not fully functional
```

Would be nice to have, thanks.

**Comment by femueller** [comment]
From my perspective this is not a Issue of taupage, it's an issue of your Docker container.
You might want to look into this thread: https://github.com/docker/docker/issues/8631.
Seems like if you want to "solve" this you need to add it to your container(taupage) environment variables.

**Comment by dryewo** [comment]
I agree, it can be worked around by executing `export TERM=xterm` after `docker exec`, but it has to be done every time. A proper fix would be to run the container with `-t` switch.

**Comment by femueller** [comment]
Didn't know about the `-t` switch. We'll try it out and will most likely integrate it if all goes fine. Thanks for the hint!

**Comment by dryewo** [comment]
:+1:
