### ISSUE TITLE
register-in-etcd log spam

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-stups/taupage#179]
Currently the register-in-etcd (https://github.com/zalando-stups/taupage/blob/master/runtime/opt/taupage/bin/register-in-etcd.py) script spams the taupage log with every 5 seconds:

    11:53:42.000  Feb 24 10:53:42 ip-172-31-128-121 register-in-etcd: INFO: Starting new HTTP connection (1): 172.17.0.1
    11:53:47.000  Feb 24 10:53:47 ip-172-31-128-121 register-in-etcd: INFO: Starting new HTTP connection (1): localhost

Do we need to adjust the logging level of `requests`?

**Comment by hjacobs** [comment]
The urllib3 package path changed when using the `requests` library:

```
$ python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging,requests
>>> logging.basicConfig(level=logging.INFO)
>>> r = requests.get('https://example.org')
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): example.org
```

=> We need to silence it with `logging.getLogger('requests.packages.urllib3.connectionpool').setLevel(logging.WARN)`

in `taupage/__init__.py`
