### ISSUE TITLE
Monitoring logfile uploads

### ISSUE THREAD

**Issue by bocytko** [zalando-stups/taupage#185]
Is there a way to monitor if logs are actively streamed to external providers like Scalyr?
I would like to monitor if any data is sent to Scalyr and be aware of errors during this process.

I know there is a possibility to check the number of log lines in the last N minutes in Scalyr directly.

**Comment by hjacobs** [comment]
@bocytko I would go with a ZMON check: https://docs.zmon.io/en/latest/user/check-commands.html?highlight=scalyr#scalyr

**Comment by bocytko** [comment]
Sounds like an option. Thanks @hjacobs.
