### ISSUE TITLE
Add Multi-Tenant Support for AppDynamics

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando-stups/taupage#187]
provide a possibility to change the account name of the appdynamics credentials

**Comment by apfeiffer85** [comment]
APPDYNAMICS_ACCOUNT_NAME
APPDYNAMICS_ACCOUNT_GLOBALNAME 

These two variables should be configurable over the metadata (senza.yml / environment variables / #taupage-ami-config).

**Comment by femueller** [comment]
This was fixed in https://github.com/zalando-stups/taupage/pull/188
