### ISSUE TITLE
First-class sidecars support

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#196]
Kubernetes' Pods are arguably the most powerful abstraction that Google teached the world. Pods have a first class notion for running multiple containers side-by-side on the same host even sharing some resources (like directories). This [concept of sidecars](http://blog.kubernetes.io/2015/06/the-distributed-system-toolkit-patterns.html) is not new but was not supported by previous container engines, including Taupage. With this issue, I want to start the discussion how to implement support for sidecars as a first class citizen in Taupage.
## Why is it important?

Sidecars enable multi-process setups in a clean way. Right now, Taupage already is a multi-process engine, having lots of processes outside of the scope of the main container. Some examples are log agents or other monitoring agents. These are currently hardcoded into Taupage and leads to a lot of feature creep into the base image as we have to implement lots of cross-concern functionality in the base instead of abstracting it away.

On the other hand, a lot of people face the challenge of running multiple processes within a single Docker container using applications like runit. This is almost always complicated and not well supported.
## What exactly is a sidecar?

A sidecar is another Docker container, that runs on the same host than the "main" container. It runs in order to get some work done for the main container. The most common example is a log agent. The main container might produce a lot of log files and writes those to disk. A log agent sidecar would be able to parse those files and send them upstream to a central log system. This means, the log agent container needs access to the log folder of the main container.

Using sidecars allows you to plug in more features to your container in a clean way. For example, Taupage doesn't need to provide any monitoring agent in the base system. It is absolutely sufficient to run a sidecar with the monitoring agent that gets access to its metrics. This decouples the base system from all the different tools someone(tm) wants to run on it in the future. Currently we have kinda feature creep as we have to implement lots of different features directly in the base system. Our base system needs to be aware of our different monitoring tools and our different log providers - tools that others might not use. This makes it very difficult to test all features in all combinations and will never allow us to be "feature complete" since we have to implement every new wish of a user again in the base system. Allowing user's to plug in their own extensions via sidecars allows us to focus on the very base and not care about all the 1000 different vendors that someone might want to use.

Another important aspect of sidecars if the very explicit handling of failure. Having sidecars aka processes as first class citizen, allows you to describe failure behaviour of those explicitly. If you need multiple processes, currently you should use runit and hide the fact that you are running multiple processes from Taupage. With first class sidecars, it is visible to Taupage that multiple processes (containers) run and can help with failure handling in a more general way without users having to reinvent everything every time. In practice, this boils down to restart strategies, for example "if sidecar X dies, restart it", "if sidecar Y dies, stop everything" and "if main container dies, restart it and also restart all sidecars".
## What resources can be shared?
- Filesystem directories should be shareable. This allows to exchange data in a very low latency and asynchronuous way like log files or batch jobs.
- Network should be shareable. This allows one container to talk to another container directly. Especially with #195, every container would run on the same network interface which enables this sharing by default.
## How the configuration could look like?

``` yaml
runtime: Docker
source: "pierone.example.org/myteam/nginx:1.0"

sidecars:
  my_logging_sidecar:
    runtime: Docker
    source:   "pierone.example.org/myteam/sidecar-logger:1.0"
    shared_paths:
      - /var/log
  my_monitor_sidecar:
    runtime: Docker
    source:   "pierone.example.org/myteam/sidecar-monitor:1.0"
    restart_policy: shutdown_server
```

I would use a map to have names for the sidecars you can refer to for example in logging; a list would also work but makes debugging harder

Shared paths could/should use Docker's volumes features to share directories. The syntax could therefor lend on if and also allow `/source/path:/target/path:ro` definitions.

Restart policies might be a set of the following:
- `always` (default): if the sidecar crashes, just restart it
- `never`: if the sidecar crashes, leave it dead
- `shutdown_server`: if the sidecar crashes, declare everything dead and shutdown the server

In case of not using the `networking: host` option (that would be the default with #195), one should be able to define Docker links.

**Comment by sarnowski** [comment]
Of course I forgot one of the biggest advantages:

## Isolation

Each container can get resource isolation on its own. In the example of an logger agent sidecar, this agent could get a limit of 100 MB memory and only a small percentage for CPU shares so that this agent cannot go wild and influence the main application.

**Comment by ollivir** [comment]
Why sidecars though? Wouldn't the less specific enhancement to support more than one docker container per running machine serve as well, and allow for other kinds of use cases too? I do like the restart policies though, even if I don't see how a 'never' policy would ever be beneficial.

**Comment by whiskeysierra** [comment]
> Why sidecars though? Wouldn't the less specific enhancement to support more than one docker container per running machine serve as well, and allow for other kinds of use cases too?

Technically it's the same thing, but conceptually does *sidecar* capture the idea pretty well that one of your containers is the *main* thing, while the others just support it. Just saying we allow multiple docker containers will give the impression that deploying multiple applications on the same host is a valid deployment strategy (which it shouldn't be, at least not on AWS EC2).

**Comment by hjacobs** [comment]
Closing this as we'll probably never support this in Taupage and instead go with https://github.com/zalando-incubator/kubernetes-on-aws
