### ISSUE TITLE
Docker doesn't start after EC2 instance reboot

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/taupage#199]
The docker container cannot be started by Taupage after an EC2 instance reboot (from EC2 Management Console, or `sudo reboot` *or* auto-recovery).  The following error appears in the syslog:
```
Mar 31 09:10:10 ip-172-31-6-75 taupage-init: INFO: Docker run failed (try 2/3), retrying in 5s..
Mar 31 09:10:16 ip-172-31-6-75 taupage-init: Error response from daemon: Conflict. The name "taupageapp" is already in use by container 6012dd71e3bb. You have to remove (or rename) that container to be able to reuse that name.
```

This is a critical issue for planb-cassandra, as we rely on auto-recovery to bring the instances back up in case of system errors.

**Comment by a1exsh** [comment]
Would it be an appropriate fix if we check for existing container and try to start it if found, otherwise run a new one?

**Comment by femueller** [comment]
Works perfectly fine. Thanks for your PR!

**Comment by a1exsh** [comment]
Actually, it turns out that the container is really started by the docker after reboot.  We should just avoid running the docker again, in order not to spam the logs with misleading errors, but there is no point in running docker start.  I will add a commit to the PR to correct this.
