### ISSUE TITLE
Push instance user data to fullstop.

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#20]
fullstop needs the Taupage user data for audit reporting

**Comment by mrandi** [comment]
{bucket-name}/{account-id}/{region-id}/{year}/{month}/{day}/{instance-id}-{timestamp}/taupage.yaml

**Comment by hjacobs** [comment]
Change of plans: fullstop. will now provide a REST endpoint to push user data to

**Comment by mrandi** [comment]
endpoint is: 
POST /api/instances/logs

schema model:

```json
{
  "accountId": "string",
  "instanceBootTime": "2015-05-26T08:43:13.533Z",
  "instanceId": "string",
  "logData": "string",
  "logType": "string",
  "region": "string"
}
```

log type are USER_DATA and AUDIT_LOG

**Comment by femueller** [comment]
Apparently this is fixed already.
