### ISSUE TITLE
Rename /etc/zalando.yaml to /etc/taupage.yaml

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#22]

**Comment by apfeiffer85** [comment]
Which files have to modify ? 
I know the following files: 

https://github.com/zalando-stups/taupage/blob/master/runtime/opt/zalando/init.d/11-register-logentries-agent.sh#L24

https://github.com/zalando-stups/taupage/blob/master/runtime/opt/zalando/init.d/12-register-scalyr-agent.sh#L24

https://github.com/zalando-stups/taupage/blob/master/runtime/opt/zalando/init.d/10-prepare-disks.py#L14

https://github.com/zalando-stups/taupage/blob/master/runtime/opt/zalando/init.d/13-start-berry.sh#L4

https://github.com/zalando-stups/taupage/blob/master/runtime/opt/zalando/runtime/Docker#L3

**Comment by apfeiffer85** [comment]
Full list (i guess):

./runtime/opt/zalando/bin/configure-ssh
./runtime/opt/zalando/init.d/12-register-scalyr-agent.sh
./runtime/opt/zalando/init.d/13-start-berry.sh
./runtime/opt/zalando/init.d/10-prepare-disks.py
./runtime/opt/zalando/init.d/11-register-logentries-agent.sh
./runtime/opt/zalando/runtime/Docker
./runtime/opt/zalando/init.sh
./runtime/etc/newrelic/nrsysmond.cfg
./runtime/etc/audit/audit.rules
./runtime/usr/lib/python2.7/dist-packages/cloudinit/handlers/zalando_ami_config.py

**Comment by hjacobs** [comment]
I renamed it in berry too
