### ISSUE TITLE
Add support for GPU-based instances

### ISSUE THREAD

**Issue by elezar** [zalando-stups/taupage#240]
For machine learning applications, it would be useful to have access to the AWS GPU instances.

Note that the installation of CUDA is delegated to the docker images, and thus the only overhead added to the AMI iteself is the NVIDIA driver. This means that additional space requirements are reduced. What are the limitations for STUPS AMIs?
- Image generation: 
  - Install the NVIDIA driver.
- Runtime (when running on a g2.2xlarge): 
  -  Ensure that relevant device nodes are created.
  -  Modify the docker launch parameters to map devices and drivers to docker container.
- Testing:
  - Create a simple test GPU-based docker image to test the driver installation.
  - Ensure that the driver does not interfere on instances where no GPU devices are present.

Note that `g2.2xlarge` instances are required to run GPU applications on AWS. I must still confirm whether this is a strict requirement when building the AMI.

References:
- NVIDIA docker discussion on installing drivers on AWS: https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2
- Arguments for mapping drivers and devices to docker containers: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
- Creating device nodes when X11 is not present: http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications

**Comment by fatz** [comment]
@elezar, @jbellmann guess this can be closed now

**Comment by elezar** [comment]
Yes. Thanks @fatz. Closing this as it was addressed in #365
