### ISSUE TITLE
net.core.somaxconn kernel parameter is not whitelisted

### ISSUE THREAD

**Issue by CVirus** [zalando-stups/taupage#241]
When trying to edit net.core.somaxconn in the sysctl block of taupage, you'll get the following error:

`You are not allowed to configure the sysctl parameters ['net.core.somaxconn']`

**Comment by szuecs** [comment]
This is a simple change, that you already did.
Please create a PR for this issue, it would be good to merge.

Thanks and all the best, sandor

**Comment by szuecs** [comment]
Thanks for your PR
