### ISSUE TITLE
Support disabling THP in the kernel

### ISSUE THREAD

**Issue by CVirus** [zalando-stups/taupage#242]
Some apps (like redis) require Transparent Huge Pages (THP) support to be disabled in the kernel, as shown in the following warning msg from redis:

`# WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.`

**Comment by szuecs** [comment]
Please do it similar to sysctl:
Create a whitelist which paths in /sys and /proc you are allowed to change.
Create a function that use the yaml structure to echo the data specified there into the specified and whitelisted file.

yaml structure could be similar to:
kernel_settings:
   /sys/kernel/mm/transparent_hugepage/enabled: never
   /sys/another/path/you/may/want: data to echo into that path

Thanks and all the Best, sandor
