### ISSUE TITLE
Configuration values with slashes for AppDynamics are not working

### ISSUE THREAD

**Issue by louis-forite** [zalando-stups/taupage#249]
In the Senza file, having the following properties `appdynamics_account_name` or  `appdynamics_account_access_key` or ` appdynamics_account_globalname`  with slashes make the AppDynamics script fail to load those properties. The following error occurs :  `-e expression #1, char 90: unknown option to `s'`.

The failing script is setup-appdynamics.sh.
`sed -i "1,$ s/http.event.accountName.*$/http.event.accountName=$config_appdynamics_account_globalname/" $properties_file` causes the issue

Related resource : 
http://stackoverflow.com/questions/9366816/sed-unknown-option-to-s

**Comment by apfeiffer85** [comment]
as slashes only happen if you use KMS encryption therefore i will integrate KMS decryption to the script. :)

**Comment by louis-forite** [comment]
Sounds good :)
