### ISSUE TITLE
Use `docker run -u application` instead of pw_uid

### ISSUE THREAD

**Issue by elgalu** [zalando-stups/taupage#25]
According to [docs Username is also accepted](https://docs.docker.com/reference/run/#user) **-u="": Username or UID** so no need to [calculate UID](https://github.com/zalando-stups/taupage/blob/1cdc5b207fa172040a6698a3238f25ad63ad0a61/runtime/opt/zalando/runtime/Docker#L40) programmatically any more.

**Comment by femueller** [comment]
I've marked this as an enhancement, since it currently doesn't bother us going forward.

**Comment by elgalu** [comment]
Thanks for replying. I'm not quite sure yet but there is a chance that if the current UID that resolves to 999 changes to another number (3 weeks ago was 998) it will break my containers: https://github.com/elgalu/docker-selenium/blob/0834746e0c50aebb8b7e5d120898f2240a305371/Dockerfile#L232

**Comment by elgalu** [comment]
And the error looks like this: `unknown uid 998: who are you?`

**Comment by femueller** [comment]
Did you try to start the application with the  `root: true` option in your senza yaml definition?
http://docs.stups.io/en/latest/components/taupage.html#how-to-configure-the-ami
Some applications aren't able to start in a docker container as a custom user. Therefore it's sometimes necessary to run them as root.

**Comment by elgalu** [comment]
I adapter my docker-selenium to launch without root and that's no longer the problem, it doesn't need root to `docker run` I'm just concerned that as soon as the UID changes it may stop working and prefer to get ahead by removing the UID and using just the username.

**Comment by femueller** [comment]
As this doesn't seem to be an issue right now. I'll close this ticket. The UID is still 998.
