### ISSUE TITLE
Resize volume if filesystem has free space

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando-stups/taupage#252]
Recently, when running a Spilo with a larger sizes EBS volume than the snapshot it was based upon, it required a manual `resize2fs`

Proposal:
- If the mounted filesystem does not need to be formatted
- If the formatted filesystem is smaller than the volume
- Then resize2fs

**Comment by slitsche** [comment]
+1
We also need this for scaling up planb-cassandra instances.

**Comment by feikesteenbergen** [comment]
Feature is merged.
