### ISSUE TITLE
Consul Appliance

### ISSUE THREAD

**Issue by Otann** [zalando-stups/taupage#256]
Hello!

I saw there is a way to provide `etcd` cluster url so I was wondering, could there be the same feature for consul in the future?

I've made consul appliance repo in GHE, which may be used freely by other teams to create Consul Cluster with single senza command.

**Comment by szuecs** [comment]
1. We are rebuilding taupage, such that you can enhance it with sidecar containers, such that you build this within an optional sidecar container.
2. An appliance that is on GHE does not help this OpenSource project. Why did you choose to have it internal and not build it as OpenSource?

**Comment by Otann** [comment]
1. Sidecars would perfectly solve the issue! How far away is this on your timeline?

2. We did not had such decision initially, because we were trying to just see if it will work for us and only then abstracted it to be reused. But I like your idea, I'll talks to Lauri about it, because it involves moving to opensource registry from internal pierone.

**Comment by szuecs** [comment]
1. We think we get a alpha, and hopefully beta, in Q3 2016
2. Cool thanks!

**Comment by Raffo** [comment]
Due to change of plans, we are not adding new features to the current Taupage and NOT building the new Taupage. We will thus not support this feature request.
