### ISSUE TITLE
DNS resolution timeout

### ISSUE THREAD

**Issue by bocytko** [zalando-stups/taupage#286]
Following explicit timeout settings in #153 - what's the DNS resolution timeout currently? For JVM apps it can't be set programmatically and the JVM inherits values from the OS.

A proven value we used in the data centers is `1 second` - `options timeout:1`.

**Comment by szuecs** [comment]
I don't know if we can change it.
We are only using the defaults.

$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.31.0.2
search eu-central-1.compute.internal

**Comment by bocytko** [comment]
Why not set the timeout in `/etc/resolvconf/resolv.conf.d/base` or `tail` and apply with `resolvconf -u`?

**Comment by szuecs** [comment]
Yes, this would help

**Comment by Raffo** [comment]
The current default timeout is 5 seconds. Also, we don't use an additional nameserver.
