### ISSUE TITLE
Auto-resizing filesystem might fail 

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/taupage#291]
Back in #252 automatic resizing of filesystem was introduced.

I'm currently testing on an older version of Taupage, so I have to run resize2fs manually after starting with bigger EBS volume attached instead of the old one.  What I see is that the tool might complain and refuse to run like this (the device was manually unmounted prior to running the command):
```
oshulgin@ip-172-31-128-15:~$ sudo resize2fs /dev/xvdf
resize2fs 1.42.9 (4-Feb-2014)
Please run 'e2fsck -f /dev/xvdf' first.
```
So then I do fsck, as suggested, which takes some time (this was a 512GB volume):
```
oshulgin@ip-172-31-128-15:~$ time sudo e2fsck -f /dev/xvdf
e2fsck 1.42.9 (4-Feb-2014)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/xvdf: 747/33554432 files (18.7% non-contiguous), 61713444/134217728 blocks

real	0m43.366s
user	0m0.912s
sys	0m0.037s
```
And then I can actually resize:
```
oshulgin@ip-172-31-128-15:~$ sudo resize2fs /dev/xvdf
resize2fs 1.42.9 (4-Feb-2014)
Resizing the filesystem on /dev/xvdf to 157286400 (4k) blocks.
The filesystem on /dev/xvdf is now 157286400 blocks long.
```

I've seen this in 2 out of 2 attempts with bigger volumes on once-busy test systems, so I feel that the naive way to run might not work 100% of the time (though, it seems to work on other less busy test systems).

I think we should either do fsck or pass -f to resize2fs itself.

**Comment by szuecs** [comment]
We should use fsck, if threre is no good reason to omit this.
