### ISSUE TITLE
Allow Customer Plugins to be added for AppDynamics Monitoring

### ISSUE THREAD

**Issue by cgmv** [zalando-stups/taupage#294]
I would like to be able to add custom plugins for monitoring into `/opt/proprietary/appdynamics-machine/monitors`. This would allow to send customer metrics about an application not running in a JVM.

**Use-Case:**
I am using [Consul](consul.io) for cluster orchestration - since its written in GO there agent support possible. Instead of running a binary file my scripts interfaces with Docker running `docker exec taupage consul members` later a shell script will evaluates the results and appdynamics pics them up.

**Comment by szuecs** [comment]
I would like to postpone it to the next Taupage version. Taupage will be rebuild such that it makes features like this easier to implement.

**Comment by cgmv** [comment]
@szuecs when is the next version of taupage to be expected?

**Comment by szuecs** [comment]
For production usage, not before Q4 2016

**Comment by apfeiffer85** [comment]
currently we're mounting the AppD directory (.../appdynamics-machine/monitors) for extensions as "rw" to the docker container ( /agents/extensions ) so you are able to install extensions be yourself.
