### ISSUE TITLE
Scalyr agent is installed on instance start -> should be baked into the AMI

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#30]
Check the following process list:

4     0  1237     1  20   0   4440   644 wait   Ss   ?          0:00 /bin/sh -e -c /opt/zalando/init.sh 2>&1 | logger -t zalando-init /bin/sh
0     0  1238  1237  20   0   4440   704 wait   S    ?          0:00  \_ /bin/sh /opt/zalando/init.sh
0     0  1431  1238  20   0   4440   656 wait   S    ?          0:00  |   \_ /bin/sh ./init.d/81-register-scalyr-agent.sh
4     0  1458  1431  20   0  18020  1640 wait   S    ?          0:00  |       \_ bash /opt/zalando/installfiles/install-scalyr-agent-2.sh --set-api-key 0xxx --star
0     0  1781  1458  20   0  61228 32288 poll_s S    ?          0:00  |           \_ apt-get -y install scalyr-agent-2
0     0  1786  1781  20   0 182260  4396 poll_s S    ?          0:00  |               \_ /usr/lib/apt/methods/https

**Comment by apfeiffer85** [comment]
Now Scalyr setup runs at the build process

**Comment by femueller** [comment]
Related:
https://github.com/zalando-stups/taupage/commit/a3857fb89ec8a327ee69fd1ea55c67ec2aea64df
https://github.com/zalando-stups/taupage/commit/348e4f4461d8391d6207950ce33b7c1a6a85283e
https://github.com/zalando-stups/taupage/commit/6d1f65704a276b85a222077ab6639b05cf05da63
