### ISSUE TITLE
Use internal health check for determining when to report success to CF

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#31]
Allow to specify a health endpoint to taupage, so that we do not blindly send a SUCCESS to CF only because the docker container started but also because this health endpoint returned true

Something like:
```
health_endpoint: 8080:/health
```

**Comment by hjacobs** [comment]
:+1: Senza could automatically fill this new "health check" Taupage Config property from the associated ELB health check settings (if an ELB is defined in the Senza definition YAML)

**Comment by sarnowski** [comment]
can you also implement #35 when your at it?

**Comment by hjacobs** [comment]
I'm closing this Taupage issue as we can track the Senza implementation with https://github.com/zalando-stups/senza/issues/56
