### ISSUE TITLE
Auto decrypt environment variables using KMS

### ISSUE THREAD

**Issue by Jan-M** [zalando-stups/taupage#32]
It would be a nice feature if Taupage image would decrypt environment variables using Amazons 'kms' before setting them for the docker run time.

This would basically solve storing credentials and handling them for a lot of frameworks.

**Comment by hjacobs** [comment]
+1

**Comment by hjacobs** [comment]
environment variable values starting with "aws:kms:" should be decrypted automatically like Friboo does it (https://github.com/zalando-stups/friboo/blob/master/src/org/zalando/stups/friboo/config.clj#L77)

**Comment by hjacobs** [comment]
This introduced a new bug:  zalando-init:     if val.startswith(AWS_KMS_PREFIX): AttributeError: 'bool' object has no attribute 'startswith'

**Comment by hjacobs** [comment]
fixed and works, very brief doc here: http://docs.stups.io/en/latest/components/taupage.html#environment
