### ISSUE TITLE
Add OSQuery to Taupage

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#33]
OSQuery[0] is a nice tool from facebook that allows for querying information about servers in a SQL like manner.

[0] https://osquery.io/

**Comment by femueller** [comment]
@sarnowski What's the purpose behind that idea?
There is already already tools like:
* [Facter](https://puppetlabs.com/facter)
* [facterpy](https://github.com/knorby/facterpy)

From my perspective it provides the same information with a different syntax. 
Personally I'm a big fan of Facter, which is also used by Puppet for example.

**Comment by femueller** [comment]
As discussed with @hjacobs we don't really see a reason why we should run OSQuery, Facter or any other tool like this at the moment.
If it's necessary we can re-open the issue.
