### ISSUE TITLE
ztoken issues hindering deployment

### ISSUE THREAD

**Issue by LappleApple** [zalando-stups/taupage#363]
[From Search teams/Poirot+Boost, issue initially faced by @adichad; we believe we've found a medium-level solution, but request a long-term solution to avoid future blockers to deployment]:

according to IAM team, new stups (ztoken and zign) return jwt tokens, and plan-b local tokeninfo service does not yet support jwt tokens. this is preventing curl calls to deployed edge instances, as edge uses plan-b local tokeninfo.

trying all-access.py also fails:

./all_access.py ci-artisan-poirot

Trying to detect your stups-mint bucket... [zalando-stups-mint-490436819829-eu-central-1]

Fetching credentials for [ci-artisan-poirot] from [zalando-stups-mint-490436819829-eu-central-1]... JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)

Error: Unable to fetch credentials

*******
[Response by @csenol]
On 20 January 2017 at 15:38, Aditya Chadha <aditya.chadha@zalando.de> wrote:

    ./all_access.py ci-artisan-poirot

Error message says
JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)

This works

    ./all_access.py live-edge-poirot                       
    Trying to detect your stups-mint bucket... [zalando-stups-mint-490436819829-eu-central-1]
    Fetching credentials for [live-edge-poirot] from [zalando-stups-mint-490436819829-eu-central-1]... OK
    Requesting token for [uid] from [https://token.services.auth.zalando.com/oauth2/access_token?realm=/services]... OK
    {"access_token":"eyJraWQiOiJpa25EIiwiYWxnIjoiR

I checked client.json in artisan AND ....
 

This is one of the funniest bug in Zalando.

"client_secret":"11Dsdt}dDYmvtwhv24olML4-2CZ1SFek"}

I issued a password rotation. It should be fixed in 20 minutes

**Comment by Raffo** [comment]
It's fixed in master, will be released next week.

**Comment by Raffo** [comment]
Closing as it is released.
