### ISSUE TITLE
Update Docker to 1.12+

### ISSUE THREAD

**Issue by ovolynets** [zalando-stups/taupage#366]
I assume there are a few things fixed in 1.12 that are related to this thread:

https://github.com/docker/docker/issues/6396

namely forwarding ssh socket to the docker container.

**Comment by marky-mark** [comment]
We would like to use the docker healthcheck

**Comment by hjacobs** [comment]
We don't plan to update the Docker version on Taupage as there are no problems and the health check is a  new feature. We would only upgrade if this gets more support/votes and solves an actual pain, otherwise Taupage stays in "maintenance mode" (no new features, only bug fixes). From the README:

> While we do not consider Taupage to have reached its end of life, we are currently not planning to add new features or extend its functionalities. We will consider any pull request, but we do not plan to directly work on enhancements.

**Comment by elezar** [comment]
Just for reference, #365 has updated the Docker version to 1.12. I suppose that this issue can then be closed?

**Comment by Raffo** [comment]
Yes, let's close it.
