### ISSUE TITLE
Don't fail when erase_on_boot is not set and ec2:DescribeTags and ec2:DeleteTags are not available

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/taupage#388]
Some time ago this was introduced:
https://github.com/zalando-stups/taupage/blob/8d5d0b7efad1f3cab563fb9da449cd0e92a0944b/runtime/opt/taupage/init.d/10-prepare-disks.py#L223

I have an application that explicitly mounts a volume (specified in Taupage User Data).

This change causes my application to fail to start up when switched to the newer Taupage version. 

While this can be fixed, for example, by adding `erase_on_boot: False` into Taupage User Data, or by adding `ec2:DescribeTags` and `ec2:DeleteTags` permissions to the application IAM Role, it's still annoying. It's a regression that ideally shouldn't have been introduced.

Taupage version where it works: `Taupage-AMI-20161109-140716`
Taupage version where it breaks: `Taupage-AMI-20170306-140613` and the following

(Taupage docs: http://stups.readthedocs.io/en/latest/components/taupage.html#mounts)

Could you please consider wrapping this part in `try`, for example, to avoid breaking existing setups?

**Comment by Raffo** [comment]
Also to be considered: the documentation is wrong as you need the role to describe and delete tags even if you are not interested in the erase on boot functionality, but just want to write a volume.

**Comment by Raffo** [comment]
@dryewo We updated the documentation to reflect the necessary change of permission (https://github.com/zalando-stups/documentation/pull/116). We don't want to introduce any implicit exception handling as the new permissions needed are in all cases the one specified. Also, the change is to make possible to avoid the previous "magic" behavior which causes some issues with erasing volume, so this original change was mostly for the safety of the data and I would not introduce unnecessary changes there.
