### ISSUE TITLE
Log rotation for `docker.log` file is failing

### ISSUE THREAD

**Issue by kanuku** [zalando-stups/taupage#396]
Hi there, we are running into the following problem when using taupage:

**version:Taupage-AMI-20170418-074252**
**Problem**: Machines had no disk space available anymore and this resulted malfunctioning of  services.

```sh
~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G   12K  3.9G   1% /dev
tmpfs           799M  368K  798M   1% /run
/dev/xvda1      7.8G  7.8G     0 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            3.9G  188K  3.9G   1% /run/shm
none            100M  4.0K  100M   1% /run/user
none            7.8G  7.8G     0 100% /var/lib/docker/aufs/mnt/f7e94de47eb288380ca1dd6336ce4e6ffa561ba13c8e5179cb45b43301b256ad
shm              64M     0   64M   0% /var/lib/docker/containers/f8848753fd0aa3235243664733e5a2769daac94dc2b0fb711424629269fe574b/shm

```

```sh
/var/log/upstart# ls -lah
total 3.2G
drwxr-xr-x  2 root root   4.0K May 10 09:34 .
drwxrwxr-x 11 root syslog 4.0K May 10 09:30 ..
...... 
...... 
-rw-r-----  1 root root   3.1G May 10 09:04 docker.log
-rw-r-----  1 root root    90M May  8 21:01 docker.log.1.gz
-rw-r-----  1 root root    43K May  6 01:59 docker.log.2.gz
-rw-r-----  1 root root    23M May  5 20:10 docker.log.3.gz
-rw-r-----  1 root root    23M May  4 20:27 docker.log.4.gz
......
...... 
```

### How did we found out about this problem?
The Authorization/Authentication step in our service was returning a "Token expired" message.
When we ssh-ed into the machine, we found out that there were no space left. 

The token is probably expired because berry (or other service responsible for rotating the credentials) could not update/save the new credentials to the filesystem (because it is full). When the application then use the old credentials after the rotation attempt, those are off-course really expired.

#### This could be the reason why the rotation of the docker.log file is failing:
```sh
...processes/bagsorter-bagstore/ab875690-34c3-11e7-9b1a-cf29068d12f1, /api/sit
...inactive'}]}\" for logger syslog: write unixgram @->/dev/log: write: message too long"
```

**Comment by hjacobs** [comment]
We could reproduce the problem with long lines.

**Comment by mikkeloscar** [comment]
We can replicate this issue if the log line is more than `212912` bytes:

```
docker run -d --log-driver=syslog ubuntu bash -c 'printf "x%.0s" {1..212913}'
```

**Comment by mikkeloscar** [comment]
I actually tested on an older taupage AMI, will follow up with a test on the latest one.

**Comment by mikkeloscar** [comment]
With the latest version of taupage (docker version 1.12.6) I can reproduce this issue with a log line of more than `212913` bytes (one more byte than before?)

**Comment by kanuku** [comment]
@mikkeloscar we have an example of at least 168197 characters

**Comment by mikkeloscar** [comment]
In this case I'm tempted to say it's not really a Taupage issue.
I mean we could implement log rotation of `docker.log`, but if it only explodes when the lines logged by the application are unreasonable long, and the logs are lost anyway, because they are too long to be logged, then it sounds more like an application issue to me.

**Comment by kanuku** [comment]
The logs are not lost, they were simply destroyed when we stopped the machines.

**Comment by mikkeloscar** [comment]
The application logs are supposed to be in `/var/log/application.log` but if the line is too long, then it's only logged as part of the error message in `/var/log/upstart/docker.log` instead. That is what I mean by the log line being lost.

**Comment by kanuku** [comment]
FYI: We use logbook to log the input/output of the application because this information is very important for us. 

I think Taupage should take a stance regarding this matter.  Imho it should either truncate or rotate the log files, but never eat up the whole disk space.


*How can we know how much is too much?*

**Comment by szuecs** [comment]
@kanuku You could create a PR that implement log rotation. We would be happy to review it.
