### ISSUE TITLE
New Relic Servers

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/taupage#40]
Investigate if we want to support [New Relic Docker integration](https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/enabling-new-relic-servers-docker).

**Comment by femueller** [comment]
I've been contacting already NewRelic regarding some auto deregister functionality for Docker containers and EC2 instances.

**Comment by femueller** [comment]
Containers become automatically deregistered after seven days and can be also erased via the NewRelic API if somebody would like to. It's suggested to keep it like this in order to keep historical data otherwise you can remove them on your own using their API

**Comment by prayerslayer** [comment]
Would be cool to have the 7 days timeframe configurable though, because most of the time I really don't care about servers that stopped reporting > 24h ago :)

**Comment by femueller** [comment]
I've requested it at NewRelic, let's see.. :+1:

**Comment by femueller** [comment]
There are still things to clarify. Therefore it won't be merged for now.

**Comment by apfeiffer85** [comment]
After we had a talk with NewRelic we will just test the Agent again and we also try the Docker integration.
