### ISSUE TITLE
Taupage docs mention CoreOS integration

### ISSUE THREAD

**Issue by otrosien** [zalando-stups/taupage#408]
There's a note saying 'We plan to integrate CoreOS’s Rocket as a runtime for experimental use soon.' Is that true, or should we just remove the note?

**Comment by hjacobs** [comment]
We should remove the note. We are migrating to Kubernetes and will not introduce new things in Taupage.

**Comment by otrosien** [comment]
Ok, that's what I thought as well when reading it.

**Comment by otrosien** [comment]
I just realized the issue is in the wrong repo. I'm closing this and adding it in the "documentation" repo.
