### ISSUE TITLE
be forgiving on erase_on_boot not present and ec2:DescribeTags and ec2:DeleteTags not available

### ISSUE THREAD

**Issue by lotharschulz** [zalando-stups/taupage#411]
reiterating on #388: I can't see why this feature can't be implemented backwards compatible.

https://github.com/zalando-stups/taupage/blob/master/runtime/opt/taupage/init.d/10-prepare-disks.py#L229 could be taken out of if scope.

cc @hjacobs as we discussed this morning about that.

**Comment by Raffo** [comment]
Can you please create a PR for this? There was an original idea of what to implement in #388 from @dryewo .

**Comment by lotharschulz** [comment]
@Raffo : I propose to tackle this with https://github.com/zalando-stups/taupage/pull/412

**Comment by Raffo** [comment]
This was implemented in #413
