### ISSUE TITLE
Missing logs on log rotation

### ISSUE THREAD

**Issue by cpeik** [zalando-stups/taupage#417]
Background
---

We see missing logs for a couple of seconds when log rotation is done.

```
cpeikert@ip-172-31-134-88:/var/log$ tail -n 1 application.log.1 | cut -b 1-15
Jul  6 09:17:14
cpeikert@ip-172-31-134-88:/var/log$ head -n 1 application.log | cut -b 1-15
Jul  6 09:17:22
```

I assume this is because of the default `logrotate` settings that we cannot override via Taupage config. [There](https://github.com/zalando-stups/taupage/blob/master/runtime/etc/logrotate.d/application) `copytruncate` is configured:

>        copytruncate
>               Truncate the original log file to zero size in place after creating a copy, instead of moving the old log file and optionally creating a new one.  It can be used when some program cannot be told to close  its  logfile
>               and  thus  might  continue  writing  (appending) to the previous log file forever.  Note that there is a very small time slice between copying the file and truncating it, so some logging data might be lost.  When this
>               option is used, the create option will have no effect, as the old log file stays in place.

 
Proposed Solution
---

Make `copytruncate` configurable.

BTW:

We would like to unset `delaycompress`, too. It almost doubles the disk usage for logs and thus we can keep less logs because of this. 

>        delaycompress
>               Postpone  compression  of  the previous log file to the next rotation cycle.  This only has effect when used in combination with compress.  It can be used when some program cannot be told to close its logfile and thus
>               might continue writing to the previous log file for some time.

**Comment by cpeik** [comment]
https://github.com/zalando-stups/taupage/issues/254 is related

**Comment by tuxlife** [comment]
merged
