### ISSUE TITLE
Daily cron job `apt` starves our application from resources

### ISSUE THREAD

**Issue by mo-gr** [zalando-stups/taupage#439]
taupage contains the default ubuntu cron jobs. One of them is `apt` (`/etc/cron.d/apt`). This daily job is very resource hungry and even though it es internally reniced (to 10), it creates so much load on the system, that we observe regular instance failures due to missed health checks on our application (tailor).

Every morning between 8:25 and 8:55 we observe huge latency spikes, which frequently lead to ASGs terminating instances.

The aforementioned apt-job is executed at 8:25 and does a random sleep between 0 and 30 minutes.

When we manually disable the apt-job, we neither see the huge latency spikes nor do we see the ASG terminating instances.

Since taupage is intended as an "immutable" base OS, I don't see any reason to run the daily `apt` job in the first place. Therefore I would recommend completely disabling this job on taupage. 

I would also appreciate if you could check all the other daily, weekly and monthly cron jobs and disable those, that are not necessary due to taupages nature.

**Comment by Joneser** [comment]
Is there any plan for this to be worked on? We are seeing the same issues mentioned above and would love to see it resolved, the solution mentioned in #440 would certainly mitigate our problems.

**Comment by aermakov-zalando** [comment]
Fixed in #449.
