### ISSUE TITLE
Add support to Amazon Time Sync Service

### ISSUE THREAD

**Issue by Cesarla** [zalando-stups/taupage#475]
Hi,

My team is experience some NTP drifts with Taupage. This is specially harmful since we are using Cassandra and the writes that happened in the past are ignored by design. (Long history short, some writes are being lost)

The current workaround is restarting the ntp daemons through tmux ssh. It works but it's a manual process and error-prone.

AWS has released *Amazon Time Sync Service*:

> a time synchronization service delivered over Network Time Protocol (NTP) which uses a fleet of redundant satellite-connected and atomic clocks in each region to deliver a highly accurate reference clock

https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/

It looks really promising and it would help us to reduce the ntp deltas to the minimun.

**Comment by f-sander** [comment]
This would fix LOG-1-1 in GDPR risk assessment for all deployments using taupage.

**Comment by aermakov-zalando** [comment]
We'll fix this issue in CW15.
