### ISSUE TITLE
Add support for variable expansion from the user data

### ISSUE THREAD

**Issue by lmineiro** [zalando-stups/taupage#488]
To the best of my knowledge, the user data is static and can be found under /etc/taupage.yaml

Some use cases could benefit from having some basic variable expansion, based on a limited, well-known set of variables.

For [PlanB Cassandra](https://github.com/zalando-stups/planb-cassandra) each node has its own unique User Data but the only difference is the EBS volume name, for example:
```
volumes:
  ebs: {/dev/xvdf: cassandra-172.31.128.40}
```

Some tools that perform EC2 orchestration would benefit if the User Data was just a template and each instance would expand the known variables. For the above example, this would be something like:
```
volumes:
  ebs: {/dev/xvdf: cassandra-${local-ipv4}}
```

If this sounds useful, I propose an initial implementation with the following variables, directly from the metadata service - http://169.254.169.254/latest/meta-data/:
* local-ipv4
* hostname
* public-ipv4
* public-hostname

This would go into the get_config() method in https://github.com/zalando-stups/taupage/blob/master/runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py providing the expansion for all calls already depending on this method. Any other requirements, like having access to the raw file, could still read the file /etc/taupage.yaml.

**Comment by aermakov-zalando** [comment]
Some of the init scripts are written in shell and use the `/opt/taupage/bin/parse-yaml.py`, so that has to be changed as well. However, it might also be worth considering running a script early during the boot process that would take the raw config, expand the variables and then write it to `/etc/taupage.yaml`.

**Comment by lmineiro** [comment]
I'd prefer to avoid changing the file. I believe its content should stay as pushed to the audit logs. Apart from the `parse-yaml.py` do you recall of any other place where the user data is loaded/parsed?

Would this be something worth contributing to? Currently, I have a use case that would benefit from it.

**Comment by aermakov-zalando** [comment]
If you grep for `taupage.yaml` you'll find a number of scripts that parse the config without using shared helpers, which is why I suggested simply overwriting it early at boot time. However, variable substitution only makes sense for a limited number of keys, so it's probably not a big deal.

Since this is the first time someone has requested this, would you mind explaining your use case?

**Comment by lmineiro** [comment]
It's actually the example I originally described. [PlanB Cassandra](https://github.com/zalando-stups/planb-cassandra) and some orchestration that keeps replacing nodes with other instance types, namely from the Spot market. Taupage already handles the attachment of the EBS volumes but the orchestrator can't really use the User Data from a single node since all of them have its own.

**Comment by lmineiro** [comment]
This should probably only be added with some explicit control flag, like `template: yes` to prevent any undesired expansion of existing tokens that may fit in the variable pattern `$var` / `${var}`

**Comment by aermakov-zalando** [comment]
For this use case, how are the volumes then cleaned up? Is it done by the orchestration?

**Comment by lmineiro** [comment]
PlanB Cassandra volumes have their own lifecycle. It doesn't use CloudFormation so, in a way, they're managed manually.

**Comment by aermakov-zalando** [comment]
Sorry, I forgot about this. Looks good to me, especially if the substitution is opt-in, not opt-out.
