### ISSUE TITLE
Store taupage.yaml in /meta/ to make it accessible to the running Docker container (application)

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#51]

**Comment by femueller** [comment]
@hjacobs What's the use case for this?

**Comment by hjacobs** [comment]
I think we can close this issue, I don't see the need for it (anymore).

**Comment by femueller** [comment]
This seems to be a valid request for Docker in Docker containers.

**Comment by sarnowski** [comment]
Another use-case where we just wanted to use this functionality (wasn't aware that we did not implement it yet) is the need for appliances to find the installing team. If the taupage.yaml is available in the container, an application can figure out the assigned application ID and then use it to e.g. resolve the owning team.

**Comment by apfeiffer85** [comment]
Its now integrated
