### ISSUE TITLE
tune sysctl settings

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/taupage#6]

**Comment by femueller** [comment]
This could be used as a guide:
http://www.brendangregg.com/blog/2015-03-03/performance-tuning-linux-instances-on-ec2.html

**Comment by apfeiffer85** [comment]
This is also a nice page: http://wiki.mikejung.biz/Sysctl_tweaks

**Comment by femueller** [comment]
I'll close this, because there hasn't been the need so far and we've already added necessary sysctl settings. Further will be added piece by piece if necessary.
