### ISSUE TITLE
Allow running Docker with "--read-only"

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/taupage#79]
To really have immutable servers and to decrease security risks (see http://container-solutions.com/docker-security-cheat-sheet/), we should allow running Docker containers with read-only file system (Docker "--read-only" flag).

We should probably think about making this the default setting for new applications.

**Comment by femueller** [comment]
Documentation has been added:
https://github.com/zalando-stups/documentation/commit/be37bcc3208729f24e4f73d9ae71cb60868748d7

**Comment by femueller** [comment]
readonly has been renamed to read_only here:
https://github.com/zalando-stups/taupage/commit/fd6ce64f43fdb8021e4acea3a492fc0bdefdcf84
