### ISSUE TITLE
rkhunter notifications

### ISSUE THREAD

**Issue by apfeiffer85** [zalando-stups/taupage#87]
Now we have the rkhunter integration and it runs every single day. 
Where and how can we send the output from rkhunter. 

Could be: 

* by mail, but therefore we also need SNS or some other SMTP-Server
* we could also send the log output (logifles) somewhere ( for example S3)

**Comment by tuxlife** [comment]
@apfeiffer85 Why not with the default logging?

mail is a very bad solution, for >100 instances.

**Comment by apfeiffer85** [comment]
currently rkhunter logs to /var/log/rkhunter ... so this still works. But how can we monitor this or get notified if there are warnings in the logfile. As i said we could push the logs to S3 and Fullstop could handle this if this is a good solution.

**Comment by tuxlife** [comment]
@apfeiffer85 sorry, i mean the remote-logging via syslog, not the file only from rkhunter.

**Comment by femueller** [comment]
Yes, logging to syslog and sending the log output to the central logging :+1:
